"""warehouse exchange history

Revision ID: 043ba47b3add
Revises: 3e0c7b6d4ded
Create Date: 2024-03-07 14:08:17.211472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '043ba47b3add'
down_revision: Union[str, None] = '3e0c7b6d4ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_exchange_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warehouse1_id', sa.Integer(), nullable=True),
    sa.Column('warehouse2_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse1_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['warehouse2_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_history_product_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse1_id'], ['warehouse.id'], name='product_history_warehouse1_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse2_id'], ['warehouse.id'], name='product_history_warehouse2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_history_pkey')
    )
    op.drop_table('warehouse_exchange_history')
    # ### end Alembic commands ###
