"""warehouse exchange history

Revision ID: 0bd743e78c57
Revises: 043ba47b3add
Create Date: 2024-03-07 14:12:34.081861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd743e78c57'
down_revision: Union[str, None] = '043ba47b3add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_exchange_history', sa.Column('from_warehouse', sa.Integer(), nullable=True))
    op.add_column('warehouse_exchange_history', sa.Column('to_warehouse', sa.Integer(), nullable=True))
    op.drop_constraint('warehouse_exchange_history_warehouse2_id_fkey', 'warehouse_exchange_history', type_='foreignkey')
    op.drop_constraint('warehouse_exchange_history_warehouse1_id_fkey', 'warehouse_exchange_history', type_='foreignkey')
    op.create_foreign_key(None, 'warehouse_exchange_history', 'warehouse', ['to_warehouse'], ['id'])
    op.create_foreign_key(None, 'warehouse_exchange_history', 'warehouse', ['from_warehouse'], ['id'])
    op.drop_column('warehouse_exchange_history', 'warehouse2_id')
    op.drop_column('warehouse_exchange_history', 'warehouse1_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_exchange_history', sa.Column('warehouse1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('warehouse_exchange_history', sa.Column('warehouse2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warehouse_exchange_history', type_='foreignkey')
    op.drop_constraint(None, 'warehouse_exchange_history', type_='foreignkey')
    op.create_foreign_key('warehouse_exchange_history_warehouse1_id_fkey', 'warehouse_exchange_history', 'warehouse', ['warehouse1_id'], ['id'])
    op.create_foreign_key('warehouse_exchange_history_warehouse2_id_fkey', 'warehouse_exchange_history', 'warehouse', ['warehouse2_id'], ['id'])
    op.drop_column('warehouse_exchange_history', 'to_warehouse')
    op.drop_column('warehouse_exchange_history', 'from_warehouse')
    # ### end Alembic commands ###
