"""warehouse shopping cart

Revision ID: 3e0c7b6d4ded
Revises: f3d40f344e7d
Create Date: 2024-03-06 19:33:17.078358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0c7b6d4ded'
down_revision: Union[str, None] = 'f3d40f344e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppingcart', 'summa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppingcart', sa.Column('summa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
