"""warehouse data category

Revision ID: 53ae367fc932
Revises: 6f9e29f3b292
Create Date: 2024-03-06 16:59:03.565038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ae367fc932'
down_revision: Union[str, None] = '6f9e29f3b292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('warehouse', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouse', 'warehouse_category', ['category_id'], ['id'])
    op.drop_constraint('warehouse_data_category_id_fkey', 'warehouse_data', type_='foreignkey')
    op.drop_column('warehouse_data', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_data', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('warehouse_data_category_id_fkey', 'warehouse_data', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_column('warehouse', 'category_id')
    op.drop_table('warehouse_category')
    # ### end Alembic commands ###
