"""shopping cart status paid

Revision ID: 65f52738746b
Revises: 57837b1261f1
Create Date: 2024-03-04 18:44:16.300709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f52738746b'
down_revision: Union[str, None] = '57837b1261f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart_status', sa.Column('paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart_status', 'paid')
    # ### end Alembic commands ###
