"""update

Revision ID: 6f9e29f3b292
Revises: dc0206670d5e
Create Date: 2024-03-06 16:10:58.180105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9e29f3b292'
down_revision: Union[str, None] = 'dc0206670d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_location')
    op.drop_table('warehouse_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='warehouse_type_category_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name='warehouse_type_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='warehouse_type_pkey')
    )
    op.create_table('product_location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_location_product_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name='product_location_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_location_pkey')
    )
    op.drop_table('warehouse_data')
    # ### end Alembic commands ###
