"""resource amount

Revision ID: 7b91f62153b3
Revises: 840156734373
Create Date: 2024-03-18 15:36:37.194646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b91f62153b3'
down_revision: Union[str, None] = '840156734373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reciept_for_products', sa.Column('resource_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reciept_for_products', 'resource_amount')
    # ### end Alembic commands ###
