"""warehouse shopping cart

Revision ID: 96cf6a63f9ab
Revises: ed6bfa4416ae
Create Date: 2024-03-06 19:09:48.097707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cf6a63f9ab'
down_revision: Union[str, None] = 'ed6bfa4416ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
