"""warehouse shopping cart

Revision ID: ed6bfa4416ae
Revises: c5406d7b05f3
Create Date: 2024-03-06 19:01:21.991263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6bfa4416ae'
down_revision: Union[str, None] = 'c5406d7b05f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppingcart', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shoppingcart', 'warehouse', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoppingcart', type_='foreignkey')
    op.drop_column('shoppingcart', 'warehouse_id')
    # ### end Alembic commands ###
