"""warehouse shopping cart

Revision ID: f3d40f344e7d
Revises: 96cf6a63f9ab
Create Date: 2024-03-06 19:27:54.642512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d40f344e7d'
down_revision: Union[str, None] = '96cf6a63f9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppingcart', sa.Column('summa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppingcart', 'summa')
    # ### end Alembic commands ###
